unbind r
unbind C-b
bind r source-file ~/.tmux.conf

set -g prefix C-a
bind C-a send-prefix

set -g mouse on

set-option -g status-position top

bind -n M-c new-window
bind -n M-x kill-window
bind -n M-n next-window
bind -n M-p previous-window


set -g mouse on
set -g default-terminal "tmux-256color"
set-option -g status-position top # This moves the bar to the top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu' # Add this line if you want CPU load

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_status_modules_left "session" 
set -g @catppuccin_status_modules_right "directory cpu date_time" # Using 'cpu' module from tmux-cpu

run '~/.tmux/plugins/tpm/tpm'
