unbind r
unbind C-b
bind r source-file ~/.tmux.conf

set -g prefix C-a
bind C-a send-prefix

set -g mouse on

set-option -g status-position top

bind c new-window
bind x kill-window
bind n next-window
bind p previous-window


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Configure the Catppuccin plugin
set -g @catppuccin_flavor "mocha" # latte, frappe, macchiato, or mocha
set -g @catppuccin_window_status_style "rounded"

# Window settings
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"
set -g @catppuccin_directory_text " #{s|$HOME|~|:pane_current_path}"

# Status bar modules
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

#run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux


run '~/.tmux/plugins/tpm/tpm'
